'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.235
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On



<Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
 Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")>  _
Partial Public NotInheritable Class app
    Inherits Global.System.Configuration.ApplicationSettingsBase
    
    Private Shared defaultInstance As app = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New app()),app)
    
    Public Shared ReadOnly Property [Default]() As app
        Get
            Return defaultInstance
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("\\Dxiburg09w025\sqa$\SQA\ISAMSS\attachments")>  _
    Public ReadOnly Property AttachmentPath() As String
        Get
            Return CType(Me("AttachmentPath"),String)
        End Get
    End Property
    
    <Global.System.Configuration.ApplicationScopedSettingAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Configuration.DefaultSettingValueAttribute("Dxiburg09w025")>  _
    Public ReadOnly Property TargetComputerName() As String
        Get
            Return CType(Me("TargetComputerName"),String)
        End Get
    End Property
End Class
